# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-16 13:09
from __future__ import unicode_literals

from django.db import migrations, models
import oscar.models.fields.autoslugfield


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0014_auto_20180316_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productclass',
            name='name',
            field=models.CharField(max_length=127, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='productclass',
            name='slug',
            field=oscar.models.fields.autoslugfield.AutoSlugField(blank=True, editable=False, max_length=127, populate_from='name', unique=True, verbose_name='Slug'),
        ),
    ]
