# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-16 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0015_auto_20180316_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attributeoptiongroup',
            name='name',
            field=models.CharField(max_length=127, verbose_name='Name'),
        ),
    ]
