# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-16 13:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0017_auto_20180316_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attributeoption',
            name='option',
            field=models.CharField(max_length=250, verbose_name='Option'),
        ),
    ]
